---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: devsecops
  namespace: ${NAMESPACE}-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: ghcr.io/gbrandalise/learn-devsecops:pt
        imagePullPolicy: Always
        ports:
        - containerPort: 8080