apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30000
    hostPort: 30010
  - containerPort: 30001
    hostPort: 30011
#- role: worker
#- role: worker
#- role: worker