---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: ${NAMESPACE}-db
spec:
  selector:
    app: postgresql
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: devsecops-app-clusterip
  namespace: ${NAMESPACE}-app
spec:
  selector:
    app: devsecops
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
