---
apiVersion: v1
kind: Service
metadata:
  name: devsecops-app-nodeport
  namespace: ${NAMESPACE}-app
spec:
  selector:
    app: devsecops
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
  type: NodePort
