apiVersion: batch/v1
kind: Job
metadata:
  name: devsecops-job
  namespace: ${NAMESPACE}-app
spec:
  ttlSecondsAfterFinished: 60 # Tempo até o job com sucesso ser removido do cluster
  # completions: 2 # Quantas vezes o job precisa ser executado com sucesso para ser finalizado
  # parallelism: 4 # Quantos pods serão executados em paralelo para esse job
  # backoffLimit: 3 # Quantas vezes os pods do job podem falhar antes do job ser considerado falho como um todo
  template:
    metadata:
      labels:
        app: devsecops-job
    spec:
      containers:
      - name: devsecops-job
        image: ghcr.io/gbrandalise/learn-devsecops:latest
        command:
        - java
        - -jar
        - /app/app.jar
        args:
        - "job"
      restartPolicy: Never