services:
  app:
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ..:/devsecops:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker