apiVersion: v1
kind: Pod
metadata:
  name: devsecops
spec:
  containers:
    - name: api
      image: ghcr.io/gbrandalise/learn-devsecops:latest
      imagePullPolicy: Always
      ports:
      - containerPort: 8080