apiVersion: v1
kind: Pod
metadata:
  name: devsecops-latest
spec:
  containers:
    - name: api
      image: ghcr.io/gbrandalise/learn-devsecops:latest
      imagePullPolicy: Always
      ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: devsecops-pt
spec:
  containers:
    - name: api
      image: ghcr.io/gbrandalise/learn-devsecops:pt
      imagePullPolicy: Always
      ports:
      - containerPort: 8080