apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: ghcr.io/gbrandalise/learn-devsecops:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: devsecops-secret
---
apiVersion: v1
kind: Service
metadata:
  name: devsecops
spec:
  selector:
    app: api
  ports:
  - port: 8080
    nodePort: 30000
  type: NodePort