apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-devsecops
  namespace: ${NAMESPACE}-app
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: devsecops-app-nodeport
            port:
              number: 8080
