---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: ${NAMESPACE}-db
spec:
  selector:
    matchLabels:
      app: postgresql
  serviceName: postgresql
  replicas: 2
  persistentVolumeClaimRetentionPolicy:
    whenScaled: Retain # Retain (default) = Mantém os Persistent Volumes mesmo depois de diminuir a quantidade de pods
                       # Delete = Deleta os Persistent Volumes não associados a um pod
    whenDelete: Retain # Retain (default) = Mantém os Persistent Volumes mesmo depois de deletar os pods
                       # Delete = Deleta os Persistent Volumes não associados a um pod
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:17-alpine
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: devsecops-db
        startupProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 30
          periodSeconds: 5
          failureThreshold: 2
          successThreshold: 1
          timeoutSeconds: 3
        livenessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 2
          successThreshold: 1
          timeoutSeconds: 3
        readinessProbe:
          exec:
            command:
              - /bin/bash
              - -c
              - "pg_isready -h localhost -p 5432 -U ${POSTGRES_USER_PLAIN} -d ${POSTGRES_DB_PLAIN}"
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 1
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          requests:
            cpu: 5m
            memory: 70Mi
          limits:
            cpu: 500m
            memory: 500Mi

        # Volume Mounts in Container
        volumeMounts:
        - name: devsecops-db-statefulset
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: devsecops-db-statefulset
      namespace: ${NAMESPACE}-db
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: devsecops-static-nfs
      resources:
        requests:
          storage: 500Mi
