name: DevSecOps CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Resolve dependencies
      run: BUILD_TARGET=dependency docker compose build
      
    - name: Compile sources
      run: BUILD_TARGET=compile docker compose build
      
    - name: Tests
      run: BUILD_TARGET=test docker compose build
      
    - name: Package
      run: BUILD_TARGET=package docker compose build
      
    - name: Docker Image
      run: docker compose build
