name: DevSecOps CI

on:
  push:
    branches: [ "main" ]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

  dependency:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
    - name: Resolve dependencies
      run: BUILD_TARGET=dependency docker compose build

  compile:
    runs-on: ubuntu-latest
    needs: dependency
    steps:
    - name: Compile sources
      run: BUILD_TARGET=compile docker compose build
