name: DevSecOps CI

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  resolve-dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Dependencies
      uses: docker/build-push-action@v6
      with:
        context: "{{defaultContext}}:app"
        target: dependency

  compile:
    runs-on: ubuntu-latest
    needs: [resolve-dependencies]
    steps:
    - uses: actions/checkout@v4

    - name: Compile
      uses: docker/build-push-action@v6
      with:
        context: "{{defaultContext}}:app"
        target: compile

  test:
    runs-on: ubuntu-latest
    needs: [compile]
    steps:
    - uses: actions/checkout@v4

    - name: Tests
      uses: docker/build-push-action@v6
      with:
        context: "{{defaultContext}}:app"
        target: test

  package:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - uses: actions/checkout@v4

    - name: Package
      uses: docker/build-push-action@v6
      with:
        context: "{{defaultContext}}:app"
        target: package

  build-publish-image:
    runs-on: ubuntu-latest
    needs: [package]
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
    - uses: actions/checkout@v4

    - name: Docker Image
      uses: docker/build-push-action@v6
      with:
        context: "{{defaultContext}}:app"

    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: "{{defaultContext}}:app"
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        labels: ${{ steps.meta.outputs.labels }}
