name: DevSecOps CI

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  resolve-dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Resolve dependencies
      run: BUILD_TARGET=dependency docker compose build
      
  compile:
    runs-on: ubuntu-latest
    needs: [resolve-dependencies]
    steps:
    - uses: actions/checkout@v4
    
    - name: Compile sources
      run: BUILD_TARGET=compile docker compose build
      
  test:
    runs-on: ubuntu-latest
    needs: [compile]
    steps:
    - uses: actions/checkout@v4
      
    - name: Tests
      run: BUILD_TARGET=test docker compose build
      
  package:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - uses: actions/checkout@v4
      
    - name: Package
      run: BUILD_TARGET=package docker compose build
      
  build-publish-image:
    runs-on: ubuntu-latest
    needs: [package]
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
    - uses: actions/checkout@v4
      
    - name: Docker Image
      run: docker compose build

    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Build and push Docker image
      uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
      with:
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        labels: ${{ steps.meta.outputs.labels }}
